POST http://localhost:3000/user/
Content-Type: application/json

{
    "name":"Rahul",
    "mobileNumber":"+919390058542",
    "ip_address":"192.168.1.1" 
}

###

POST http://localhost:3000/user/validateOTP/
Content-Type:application/json

{
    "userPhoneNumber":"+919390058542",
    "enteredOTP":"4609", 
    "ip_address":"fe80::1"
}